# -- Main menu --
# https://blowfish.page/docs/configuration-and-defaults/#main-menu

[[main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 10

[[main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 20

[[main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 30
